on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'paicrush'
      # Use the output from the `hello` ste
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: build images
        run: |
            docker build -t paicrush/helloworld .
